name: Run Cypress Tests

on:
  push:
    branches:
      - main  # Runs tests on push to main branch
  pull_request:
    branches:
      - main  # Runs tests on PR to main branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust if needed

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run
